version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run: go vet ./...
      - run: go test ./...
      - run:
        command: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts
