version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run:
        command: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts
        command: go vet ./...
        command: go test ./...
